import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/universal/Navbar";
import { UserProvider } from "@/app/contexts/UserContext";
import { NextStepProvider, NextStep } from 'nextstepjs'
import CustomCard from "@/components/tutorial/Card";
import { steps } from "@/app/tutorial/steps";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <NextStepProvider>
            <NextStep steps={steps} cardComponent={CustomCard}>
              <Navbar />
              {children}
              <Toaster />
            </NextStep>
          </NextStepProvider>

        </UserProvider>
      </body>
    </html>
  );
}
